"""initial schema

Revision ID: 5aaa1beaaf30
Revises: 
Create Date: 2026-05-15 07:24:18.462473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5aaa1beaaf30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_subsistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_subsistema_codigo'), 'dim_subsistema', ['codigo'], unique=True)
    op.create_table('dim_usina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('id_subsistema', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_subsistema'], ['dim_subsistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_modelo', 'id_subsistema')
    )
    op.create_index(op.f('ix_dim_usina_id_modelo'), 'dim_usina', ['id_modelo'], unique=False)
    op.create_table('fato_balanco_energia_dessem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('id_subsistema', sa.Integer(), nullable=False),
    sa.Column('valor_demanda_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_hidraulica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_pequena_hidraulica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_termica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_pequena_termica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_eolica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_fotovoltaica_wh', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_subsistema'], ['dim_subsistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'hora', 'id_subsistema')
    )
    op.create_index(op.f('ix_fato_balanco_energia_dessem_data'), 'fato_balanco_energia_dessem', ['data'], unique=False)
    op.create_index(op.f('ix_fato_balanco_energia_dessem_id_subsistema'), 'fato_balanco_energia_dessem', ['id_subsistema'], unique=False)
    op.create_table('fato_balanco_energia_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('id_subsistema', sa.Integer(), nullable=False),
    sa.Column('geracao_hidraulica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_termica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_eolica_wh', sa.Integer(), nullable=True),
    sa.Column('geracao_fotovoltaica_wh', sa.Integer(), nullable=True),
    sa.Column('carga_wh', sa.Integer(), nullable=True),
    sa.Column('intercambio_wh', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_subsistema'], ['dim_subsistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'hora', 'id_subsistema')
    )
    op.create_index(op.f('ix_fato_balanco_energia_horario_data'), 'fato_balanco_energia_horario', ['data'], unique=False)
    op.create_index(op.f('ix_fato_balanco_energia_horario_id_subsistema'), 'fato_balanco_energia_horario', ['id_subsistema'], unique=False)
    op.create_table('fato_cmo_semanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('id_subsistema', sa.Integer(), nullable=False),
    sa.Column('cmo_medio_reais_mwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cmo_carga_leve_reais_mwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cmo_carga_media_reais_mwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cmo_carga_pesada_reais_mwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['id_subsistema'], ['dim_subsistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'id_subsistema')
    )
    op.create_index(op.f('ix_fato_cmo_semanal_data'), 'fato_cmo_semanal', ['data'], unique=False)
    op.create_index(op.f('ix_fato_cmo_semanal_id_subsistema'), 'fato_cmo_semanal', ['id_subsistema'], unique=False)
    op.create_table('fato_cmo_semi_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('id_subsistema', sa.Integer(), nullable=False),
    sa.Column('cmo_reais_mwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['id_subsistema'], ['dim_subsistema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'hora', 'id_subsistema')
    )
    op.create_index(op.f('ix_fato_cmo_semi_horario_data'), 'fato_cmo_semi_horario', ['data'], unique=False)
    op.create_index(op.f('ix_fato_cmo_semi_horario_id_subsistema'), 'fato_cmo_semi_horario', ['id_subsistema'], unique=False)
    op.create_table('fato_cvu_usinas_termicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano_pmo', sa.Integer(), nullable=False),
    sa.Column('mes_pmo', sa.Integer(), nullable=False),
    sa.Column('numero_revisao', sa.Integer(), nullable=False),
    sa.Column('semana_operativa', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('id_usina', sa.Integer(), nullable=False),
    sa.Column('cvu_reais_mwh', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['id_usina'], ['dim_usina.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_inicio', 'id_usina', 'numero_revisao')
    )
    op.create_index(op.f('ix_fato_cvu_usinas_termicas_data_inicio'), 'fato_cvu_usinas_termicas', ['data_inicio'], unique=False)
    op.create_index(op.f('ix_fato_cvu_usinas_termicas_id_usina'), 'fato_cvu_usinas_termicas', ['id_usina'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fato_cvu_usinas_termicas_id_usina'), table_name='fato_cvu_usinas_termicas')
    op.drop_index(op.f('ix_fato_cvu_usinas_termicas_data_inicio'), table_name='fato_cvu_usinas_termicas')
    op.drop_table('fato_cvu_usinas_termicas')
    op.drop_index(op.f('ix_fato_cmo_semi_horario_id_subsistema'), table_name='fato_cmo_semi_horario')
    op.drop_index(op.f('ix_fato_cmo_semi_horario_data'), table_name='fato_cmo_semi_horario')
    op.drop_table('fato_cmo_semi_horario')
    op.drop_index(op.f('ix_fato_cmo_semanal_id_subsistema'), table_name='fato_cmo_semanal')
    op.drop_index(op.f('ix_fato_cmo_semanal_data'), table_name='fato_cmo_semanal')
    op.drop_table('fato_cmo_semanal')
    op.drop_index(op.f('ix_fato_balanco_energia_horario_id_subsistema'), table_name='fato_balanco_energia_horario')
    op.drop_index(op.f('ix_fato_balanco_energia_horario_data'), table_name='fato_balanco_energia_horario')
    op.drop_table('fato_balanco_energia_horario')
    op.drop_index(op.f('ix_fato_balanco_energia_dessem_id_subsistema'), table_name='fato_balanco_energia_dessem')
    op.drop_index(op.f('ix_fato_balanco_energia_dessem_data'), table_name='fato_balanco_energia_dessem')
    op.drop_table('fato_balanco_energia_dessem')
    op.drop_index(op.f('ix_dim_usina_id_modelo'), table_name='dim_usina')
    op.drop_table('dim_usina')
    op.drop_index(op.f('ix_dim_subsistema_codigo'), table_name='dim_subsistema')
    op.drop_table('dim_subsistema')
    # ### end Alembic commands ###
