"""add_descricao_to_kpi_config

Revision ID: 5dfd302a2009
Revises: b8350edb257c
Create Date: 2026-05-15 21:34:59.369119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5dfd302a2009'
down_revision: Union[str, None] = 'b8350edb257c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_config', sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_config', 'descricao')
    # ### end Alembic commands ###
