"""bigint energy columns

Revision ID: 715d04bd0c2e
Revises: 5aaa1beaaf30
Create Date: 2026-05-15 07:51:17.922333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '715d04bd0c2e'
down_revision: Union[str, None] = '5aaa1beaaf30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fato_balanco_energia_dessem', 'valor_demanda_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_hidraulica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_pequena_hidraulica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_termica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_pequena_termica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_eolica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_fotovoltaica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_hidraulica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_termica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_eolica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_fotovoltaica_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'carga_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'intercambio_wh',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fato_balanco_energia_horario', 'intercambio_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'carga_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_fotovoltaica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_eolica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_termica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_horario', 'geracao_hidraulica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_fotovoltaica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_eolica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_pequena_termica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_termica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_pequena_hidraulica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'geracao_hidraulica_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('fato_balanco_energia_dessem', 'valor_demanda_wh',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
