"""add_visivel_to_kpi_config

Revision ID: b8350edb257c
Revises: e738abacc3fa
Create Date: 2026-05-15 21:17:54.760792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8350edb257c'
down_revision: Union[str, None] = 'e738abacc3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_config', sa.Column('visivel', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_config', 'visivel')
    # ### end Alembic commands ###
