"""add_ordem_timestamps_to_kpi_config

Revision ID: e738abacc3fa
Revises: eec3c4264e9e
Create Date: 2026-05-15 21:01:37.358782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e738abacc3fa'
down_revision: Union[str, None] = 'eec3c4264e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kpi_config', sa.Column('ordem', sa.Integer(), nullable=False))
    op.add_column('kpi_config', sa.Column('criado_em', sa.DateTime(), nullable=False))
    op.add_column('kpi_config', sa.Column('atualizado_em', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kpi_config', 'atualizado_em')
    op.drop_column('kpi_config', 'criado_em')
    op.drop_column('kpi_config', 'ordem')
    # ### end Alembic commands ###
