import type { KpiConfig } from '../../types';

export const mockKpiConfigs: KpiConfig[] = [
  {
    id: 1,
    slug: 'cmo-semanal',
    titulo: 'Evolução do CMO por Subsistema',
    descricao: 'Custo Marginal de Operação semanal por subsistema do SIN',
    tipo: 'line',
    endpoint_path: '/api/kpis/cmo-semanal',
    ordem: 1,
    visivel: true,
    config_json: { unidade: 'R$/MWh', cor: '#58a6ff' },
    criado_em: '2024-01-01T00:00:00Z',
    atualizado_em: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    slug: 'balanco-horario',
    titulo: 'Mix de Geração',
    descricao: 'Balanço energético por fonte renovável e não-renovável',
    tipo: 'area',
    endpoint_path: '/api/kpis/balanco-horario',
    ordem: 2,
    visivel: true,
    config_json: { unidade: 'TWh' },
    criado_em: '2024-01-01T00:00:00Z',
    atualizado_em: '2024-01-01T00:00:00Z',
  },
  {
    id: 3,
    slug: 'renovavel',
    titulo: '% Renovável por Subsistema',
    descricao: 'Percentual de geração renovável (hidráulica + eólica + solar)',
    tipo: 'bar',
    endpoint_path: '/api/kpis/renovavel',
    ordem: 3,
    visivel: true,
    config_json: { unidade: '%', meta: 80 },
    criado_em: '2024-01-01T00:00:00Z',
    atualizado_em: '2024-01-01T00:00:00Z',
  },
  {
    id: 4,
    slug: 'cvu-usinas',
    titulo: 'Top Usinas por CVU',
    descricao: 'Ranking de usinas termelétricas por Custo Variável Unitário',
    tipo: 'bar',
    endpoint_path: '/api/kpis/cvu-usinas',
    ordem: 4,
    visivel: true,
    config_json: { unidade: 'R$/MWh', topN: 15 },
    criado_em: '2024-01-01T00:00:00Z',
    atualizado_em: '2024-01-01T00:00:00Z',
  },
  {
    id: 5,
    slug: 'perfil-demanda',
    titulo: 'Perfil Intradiário de Demanda',
    descricao: 'Curva de demanda média por hora do dia (0h–23h)',
    tipo: 'line',
    endpoint_path: '/api/kpis/perfil-demanda',
    ordem: 5,
    visivel: true,
    config_json: { unidade: 'TWh' },
    criado_em: '2024-01-01T00:00:00Z',
    atualizado_em: '2024-01-01T00:00:00Z',
  },
  {
    id: 6,
    slug: 'intercambio',
    titulo: 'Intercâmbio entre Subsistemas',
    descricao: 'Fluxo de energia entre subsistemas (+ = exportação)',
    tipo: 'bar',
    endpoint_path: '/api/kpis/intercambio',
    ordem: 6,
    visivel: true,
    config_json: { unidade: 'TWh' },
    criado_em: '2024-01-01T00:00:00Z',
    atualizado_em: '2024-01-01T00:00:00Z',
  },
  {
    id: 7,
    slug: 'cmo-patamares',
    titulo: 'CMO por Patamar de Carga',
    descricao: 'CMO segmentado por patamar: leve, médio e pesado',
    tipo: 'bar',
    endpoint_path: '/api/kpis/cmo-semanal',
    ordem: 7,
    visivel: false,
    config_json: { unidade: 'R$/MWh' },
    criado_em: '2024-01-01T00:00:00Z',
    atualizado_em: '2024-01-01T00:00:00Z',
  },
];

export const mockActiveKpiConfigs = mockKpiConfigs.filter((k) => k.visivel);
